#ifndef VFSCMD_H
#define VFSCMD_H

enum {
	VFS_CMD_OPEN = 0,	
	VFS_CMD_CLOSE,
	VFS_CMD_ADD,	
	VFS_CMD_DEL,
	VFS_CMD_INFO,
	VFS_CMD_PIPE_OPEN,
	VFS_CMD_INFO_UPDATE,
	VFS_CMD_NODE_BY_ADDR,
	VFS_CMD_NODE_BY_FD,
	VFS_CMD_NODE_BY_NAME,
	VFS_CMD_NODE_FULLNAME,
	VFS_CMD_NODE_SHORTNAME,
	VFS_CMD_KID,
	VFS_CMD_MOUNT,
	VFS_CMD_MOUNTED,
	VFS_CMD_UNMOUNT,
	VFS_CMD_MOUNT_BY_INDEX,
	VFS_CMD_MOUNT_BY_FNAME,
	FS_OPEN,
	FS_CLOSE,
	FS_REMOVE,
	FS_WRITE,
	FS_READ,
	FS_CTRL,
	FS_FLUSH,
	FS_DMA,
	FS_ADD
};

#endif
