VERSATILE_PS2KEYBD_OBJS = $(ROOT_DIR)/sbin/dev/arch/versatilepb/ps2keybd/ps2keybd.o

VERSATILE_PS2KEYBD = $(TARGET_DIR)/$(ROOT_DIR)/sbin/dev/versatilepb/ps2keybd

PROGS += $(VERSATILE_PS2KEYBD)
CLEAN += $(VERSATILE_PS2KEYBD_OBJS)

$(VERSATILE_PS2KEYBD): $(VERSATILE_PS2KEYBD_OBJS) $(LIB_OBJS)
	$(LD) -Ttext=100 $(VERSATILE_PS2KEYBD_OBJS) -o $(VERSATILE_PS2KEYBD) $(LDFLAGS) -lewokc -lc
