all: basic_libs
	@echo "all done."

basic_libs:
	cd crc32;make
	cd zlib;make
	cd openlibm;make
	cd graph;make
	cd display;make
	cd ttf;make
	cd font;make
	cd minimp3;make
	cd fb;make
	cd keyb;make
	cd mouse;make
	cd upng; make
	cd fbd;make
	cd terminal;make
	cd gterminal;make
	cd c++/stl;make
	cd c++/c++;make

clean:
	cd crc32;make clean
	cd zlib;make clean
	cd openlibm;make clean
	cd ttf;make clean
	cd terminal;make clean
	cd gterminal;make clean
	cd display;make clean
	cd font;make clean
	cd upng; make clean
	cd minimp3;make clean
	cd graph;make clean
	cd fb;make clean
	cd keyb;make clean
	cd mouse;make clean
	cd fbd;make clean
	cd c++/stl;make clean
	cd c++/c++;make clean
