target("xconsole")
    set_type("application")
    add_deps("libx", "libx++", "libupng", "libconsole", "libsconf", "libcxx")
    add_files("**.cc")        
    install_dir("apps/xconsole")
target_end()
