basic_sys:
	cd uartd; make
	cd gpio_actledd; make
	cd mbox_actledd; make
	cd soundd; make
	cd usbd; make

full_sys:
	cd fbd; make

clean:	
	cd uartd; make clean
	cd gpio_actledd; make clean
	cd mbox_actledd; make clean
	cd fbd; make clean
	cd soundd; make clean
	cd usbd; make clean
