all: 
	cd mini_uartd; make
	cd pl011_uartd; make
	cd gpio_actledd; make
	cd mbox_actledd; make
	cd fbd; make
	cd soundd; make
	cd usbd; make

clean:	
	cd mini_uartd; make clean
	cd pl011_uartd; make clean
	cd gpio_actledd; make clean
	cd mbox_actledd; make clean
	cd fbd; make clean
	cd soundd; make clean
	cd usbd; make clean
