all: 
	cd audio; make
	cd fbd; make
	cd gpio_joykeybd; make
	cd gpio_joystickd; make
	cd ms_uartd; make

clean:	
	cd audio; make clean
	cd fbd; make clean
	cd gpio_joykeybd; make clean
	cd gpio_joystickd; make clean
	cd ms_uartd; make clean
