all:
	cd xtext; make
	cd xconsole; make
	cd finder; make
	cd gtest; make
	cd wtest; make
	cd anim; make
	cd book; make

clean:
	cd xtext; make clean
	cd xconsole; make clean
	cd finder; make clean
	cd gtest; make clean
	cd wtest; make clean
	cd anim; make clean
	cd book; make clean
