all:
	cd xtext; make
	cd finder; make
	cd gtest; make
	cd xterm; make
	cd wtest; make
	cd anim; make
	cd book; make
	cd clock; make

clean:
	cd xtext; make clean
	cd finder; make clean
	cd gtest; make clean
	cd xterm; make clean
	cd wtest; make clean
	cd anim; make clean
	cd book; make clean
	cd clock; make clean
