all:
	cd gtest; make
	cd xterm; make
	cd wtest; make
	cd anim; make
	cd xread; make
	cd clock; make
	cd xcores; make
	cd xfonts; make
	cd xapps; make
	cd xfinder; make
	cd xpng; make
	cd xprocs; make
	cd xtrace; make

clean:
	cd gtest; make clean
	cd xterm; make clean
	cd wtest; make clean
	cd anim; make clean
	cd xread; make clean
	cd clock; make clean
	cd xcores; make clean
	cd xfonts; make clean
	cd xapps; make clean
	cd xfinder; make clean
	cd xpng; make clean
	cd xprocs; make clean
	cd xtrace; make clean
