all:
	cd libs; make
	cd drivers; make
	cd bin; make
	cd sbin; make
	cd xwm/opencde; make

clean:
	cd libs; make clean
	cd drivers; make clean
	cd bin; make clean
	cd sbin; make clean
	cd xwm/opencde; make clean
