all: 
	cd ttyd; make
	cd fbd; make
	cd ps2keybd; make
	cd ps2moused; make
	cd smc91c111d; make

clean:	
	cd ttyd; make clean
	cd fbd; make clean
	cd ps2keybd; make clean
	cd ps2moused; make clean
	cd smc91c111d; make clean
