basic_sys: 
	cd ttyd; make
	cd ps2keybd; make
	cd ps2moused; make
	cd smc91c111d; make

full_sys: 
	cd fbd; make

clean:	
	cd ttyd; make clean
	cd fbd; make clean
	cd ps2keybd; make clean
	cd ps2moused; make clean
	cd smc91c111d; make clean
