target("etc")
    set_type("phony")
    install_dir("etc")    
    local rootfs_dir = get_rootfsdir()
    on_build(function(target)
        os.cp(target:scriptdir().."/full/arch.rd", rootfs_dir.."etc/")
        os.cp(target:scriptdir().."/full/system.rd", rootfs_dir.."etc/")
        os.cp(target:scriptdir().."/full/x", rootfs_dir.."etc/")
    end)
target_end()
