target("emu")
    set_type("application")
    add_deps("libx", "libx++", "libupng", "libconsole", "libtextview", "libsconf", "libcxx")
    add_files("main.cpp", "src/InfoNES.cpp", "src/infoNES_Mapper.cpp", "src/InfoNES_pAPU.cpp", "src/K6502.cpp")        
    install_dir("apps/emu")
target_end()
