basic:
	cd uartd; make
	cd soundd; make
	cd usbd; make
	cd usbd.touch; make
	cd hid_keybd; make
	cd hid_moused; make
	cd hid_joystickd; make
	cd spi2uart; make
	cd wlan; make

gui:
	cd fbd; make

clean:	
	cd uartd; make clean
	cd fbd; make clean
	cd soundd; make clean
	cd usbd; make clean
	cd usbd.touch; make clean
	cd hid_keybd; make clean
	cd hid_moused; make clean
	cd hid_joystickd; make clean
	cd spi2uart; make clean
	cd wlan; make clean
