#ifndef SYSCALL_CODE_H
#define SYSCALL_CODE_H

typedef enum {
	SYSCALL_KDB,
	SYSCALL_UART_PUTCH,
	SYSCALL_UART_GETCH,

	SYSCALL_FORK,
	SYSCALL_GETPID,
	SYSCALL_EXEC_ELF,
	SYSCALL_WAIT,
	SYSCALL_YIELD,
	SYSCALL_EXIT,

	SYSCALL_PMALLOC,
	SYSCALL_PFREE,

	SYSCALL_GET_CMD,

	SYSCALL_KOPEN,
	SYSCALL_KCLOSE,
	SYSCALL_KWRITE,
	SYSCALL_KREADY,
	SYSCALL_KREAD,
	SYSCALL_KGETPID_R,
	SYSCALL_KGETPID_W,

	SYSCALL_INITRD_READ,
	SYSCALL_INITRD_FILES,
	SYSCALL_INITRD_INFO,

	SYSCALL_PFILE_NODE,
	SYSCALL_PFILE_GET_SEEK,
	SYSCALL_PFILE_SEEK,
	SYSCALL_PFILE_OPEN,
	SYSCALL_PFILE_CLOSE,

	SYSCALL_KSERV_REG,
	SYSCALL_KSERV_GET,

	SYSCALL_GET_PROCS,
	SYSCALL_GET_CWD,
	SYSCALL_SET_CWD,

	SYSCALL_SET_UID,
	SYSCALL_GET_UID
} SyscallCodeT;

#endif
