target("etc")
    set_type("phony")
    install_dir("etc")    
    local rootfs_dir = get_rootfsdir()
    on_build(function(target)
        os.cp(target:scriptdir().."/framebuffer.conf", rootfs_dir.."etc/")
    end)
target_end()
