target("etc")
    set_type("phony")
    install_dir("etc")    
    local rootfs_dir = get_rootfsdir()
    on_build(function(target)
        os.cp(target:scriptdir().."/arch.rd", rootfs_dir.."etc/")
        os.cp(target:scriptdir().."/system.rd", rootfs_dir.."etc/")
        os.cp(target:scriptdir().."/x", rootfs_dir.."etc/")
    end)
target_end()
