VERSATILE_PS2MOUSED_OBJS = $(ROOT_DIR)/sbin/dev/arch/versatilepb/ps2moused/ps2moused.o

VERSATILE_PS2MOUSED = $(TARGET_DIR)/$(ROOT_DIR)/sbin/dev/versatilepb/ps2moused

PROGS += $(VERSATILE_PS2MOUSED)
CLEAN += $(VERSATILE_PS2MOUSED_OBJS)

$(VERSATILE_PS2MOUSED): $(VERSATILE_PS2MOUSED_OBJS) $(LIB_OBJS)
	$(LD) -Ttext=100 $(VERSATILE_PS2MOUSED_OBJS) -o $(VERSATILE_PS2MOUSED) $(LDFLAGS) -lewokc -lc
