all:
	cd raspix;make
	cd miyoo;make
	cd rk3128;make
	cd versatilepb;make

extra:
	cd raspix;make extra
	cd miyoo;make extra
	cd rk3128;make extra
	cd versatilepb;make extra

sd:
	cd raspix;make sd
	cd miyoo;make sd
	cd rk3128;make sd
	cd versatilepb;make sd

clean:
	cd raspix;make clean
	cd miyoo;make clean
	cd rk3128;make clean
	cd versatilepb;make clean


