basic: 
	cd ttyd; make
	cd virtfsd; make

gui:
	cd fbd; make
	cd moused; make
	cd keybd; make

clean:	
	cd ttyd; make clean
	cd virtfsd; make clean
	cd fbd; make clean
	cd moused; make clean
	cd keybd; make clean
