basic: 
	cd ttyd; $(MAKE)
	cd virtfsd; $(MAKE)
	cd powerd; $(MAKE)

gui:
	cd fbd; $(MAKE)
	cd moused; $(MAKE)
	cd keybd; $(MAKE)
	cd snd; $(MAKE)

network:
	cd net; $(MAKE)

clean:	
	cd ttyd; $(MAKE) clean
	cd virtfsd; $(MAKE) clean
	cd fbd; $(MAKE) clean
	cd moused; $(MAKE) clean
	cd keybd; $(MAKE) clean
	cd snd; $(MAKE) clean
	cd powerd; $(MAKE) clean
	cd net; $(MAKE) clean
