all:
	cd xlog; make
	cd xterm; make
	cd xread; make
	cd xcores; make
	cd xfonts; make
	cd xapps; make
	cd xfinder; make
	cd xpng; make
	cd xprocs; make
	cd xDemo; make
	cd xwm_theme; make
	cd xtheme; make

clean:
	cd xlog; make clean
	cd xterm; make clean
	cd xread; make clean
	cd xcores; make clean
	cd xfonts; make clean
	cd xapps; make clean
	cd xfinder; make clean
	cd xpng; make clean
	cd xprocs; make clean
	cd xDemo; make clean
	cd xwm_theme; make clean
	cd xtheme; make clean
