VERSATILEPB_TTYD_OBJS = $(ROOT_DIR)/drivers/arch/arm/versatilepb/ttyd/ttyd.o

VERSATILEPB_TTYD = $(TARGET_DIR)/$(ROOT_DIR)/drivers/arm/versatilepb/ttyd

PROGS += $(VERSATILEPB_TTYD)
CLEAN += $(VERSATILEPB_TTYD_OBJS)

$(VERSATILEPB_TTYD): $(VERSATILEPB_TTYD_OBJS)
	$(LD) -Ttext=100 $(VERSATILEPB_TTYD_OBJS) -o $(VERSATILEPB_TTYD) $(LDFLAGS) -lewokc -lc
