all:
	cd xim/none; $(MAKE)
	cd xim/vkey; $(MAKE)
	cd xmouse; $(MAKE)
	cd xtouch; $(MAKE)

clean:
	cd xim/none; $(MAKE) clean
	cd xim/vkey; $(MAKE) clean
	cd xmouse; $(MAKE) clean
	cd xtouch; $(MAKE) clean
