all: drivers
	@echo "all done."

drivers:
	cd vjoystickd;make
	cd fontd;make
	cd displayd;make
	cd consoled;make

clean:
	cd vjoystickd;make clean
	cd fontd;make clean
	cd displayd;make clean
	cd consoled;make clean