all:
	cd xim/none; make
	cd xim/vkey; make
	cd xjoystick; make
	cd xmouse; make
	cd xtouch; make
	cd xwm/mac1984; make
	cd xwm/solaris; make

clean:
	cd xim/none; make clean
	cd xim/vkey; make clean
	cd xjoystick; make clean
	cd xmouse; make clean
	cd xtouch; make clean
	cd xwm/mac1984; make clean
	cd xwm/solaris; make clean
