all:
	cd xim/none; make
	cd xim/vkey; make
	cd xjoystick; make
	cd xjoymouse; make
	cd xmouse; make
	cd xtouch; make

clean:
	cd xim/none; make clean
	cd xim/vkey; make clean
	cd xjoystick; make clean
	cd xjoymouse; make clean
	cd xmouse; make clean
	cd xtouch; make clean
