#ifndef SYSCALLS_H
#define SYSCALLS_H

#define DMA_MAGIC   0xCAFECAFF

enum {
	SYS_NONE = 0,
	SYS_KPRINT, 
	//proccess memory manage
	SYS_MALLOC_EXPAND,
	SYS_MALLOC_SIZE,
	SYS_FREE,

	SYS_EXEC_ELF,
	SYS_FORK,
	SYS_THREAD,
	SYS_YIELD,
	SYS_WAIT_PID,
	SYS_USLEEP,
	SYS_EXIT,
	SYS_DETACH,
	SYS_BLOCK,
	SYS_WAKEUP,
	SYS_SIGNAL_SETUP,
	SYS_SIGNAL,
	SYS_SIGNAL_END,

	SYS_GET_PID,
	SYS_GET_THREAD_ID,

	SYS_IPC_PING,
	SYS_IPC_READY,

	SYS_PROC_GET_CMD,
	SYS_PROC_SET_CMD,
	SYS_PROC_GET_UID,
	SYS_PROC_SET_UID,

	//share memory syscalls
	SYS_PROC_SHM_GET,
	SYS_PROC_SHM_MAP,
	SYS_PROC_SHM_UNMAP,

	SYS_GET_SYS_INFO,
	SYS_GET_SYS_STATE,
	SYS_GET_VSYSCALL_INFO,
	SYS_GET_PROC,
	SYS_GET_PROCS_NUM,
	SYS_GET_PROCS,

	//map mmio memory for userspace access
	SYS_MEM_MAP,
	SYS_V2P,
	SYS_P2V,

	//internal proccess communication
	SYS_IPC_SETUP,
	SYS_IPC_CALL,
	SYS_IPC_GET_ARG,
	SYS_IPC_SET_RETURN,
	SYS_IPC_GET_RETURN,
	SYS_IPC_END,
	SYS_IPC_DISABLE,
	SYS_IPC_ENABLE,

	SYS_CORE_READY,
	SYS_CORE_PID,
	SYS_GET_KEVENT,

	SYS_INTR_SETUP,
	SYS_INTR_END,

	SYS_SEMAPHORE_ALLOC,
	SYS_SEMAPHORE_FREE,
	SYS_SEMAPHORE_ENTER,
	SYS_SEMAPHORE_QUIT,
	SYS_SOFT_INT,

	SYS_PROC_GET_GID,
	SYS_PROC_SET_GID,

	SYS_DMA_ALLOC,
	SYS_DMA_FREE,
	SYS_DMA_PHY_ADDR,
	SYS_DMA_SET,

	SYS_MMIO_RW,
	SYS_PROC_PRIORITY,
	SYS_CALL_NUM
};

#endif
