all: basic_libs
	@echo "all done."

basic_libs:
	cd socket;make
	cd ntpc;make
	cd libtinyhttpsc;make
	cd openssl;make

clean:
	cd socket;make clean
	cd ntpc;make clean
	cd libtinyhttpsc;make clean
	cd openssl;make clean
