target("xwm_opencde")
    set_type("application")
    add_files("*.cc")        
    add_deps("libx++", "libx", "libgraph", "libttf", "libfont" ,, "libupng","libsconf", "libcxx")
    install_dir("sbin/x")
target_end()
