all: drivers
	@echo "all done."

drivers:
	cd fontd;make
	cd displayd;make
	cd consoled;make
	cd vkeybd;make

clean:
	cd fontd;make clean
	cd displayd;make clean
	cd consoled;make clean
	cd vkeybd;make clean