all:arm riscv

arm:miyoo raspix rk3128 versatilepb

riscv:

miyoo:
	xmake f -p miyoo 
	xmake 

raspix:
	xmake f -p raspix
	xmake

rk3128:
	xmake f -p rk3128
	xmake

versatilepb:
	xmake f -p versatilepb
	xmake

clean:
	rm -rf build

