all: 
	cd fbd; make
	cd gpio_joykeybd; make
	cd gpio_joystickd; make
	cd rk_uartd; make

clean:	
	cd fbd; make clean
	cd gpio_joykeybd; make clean
	cd gpio_joystickd; make clean
	cd rk_uartd; make clean
