#!/bin/bash

SRC_DIR=$1
IMG_FILE=$2

if [ ! -e ${IMG_FILE} ];then
    dd if=/dev/zero of=${IMG_FILE} bs=1 count=0 seek=256M
fi
mke2fs -q -b 1024 -I 128 ${IMG_FILE}
cd ${SRC_DIR}
find . -type f | e2cp -apv -d ${IMG_FILE}:/


