target("libbsp")
    set_type("library")
    add_deps("libsd", "libarch_vpb", "libewokc")
    add_files("**.c")        
    add_includedirs("include", "../../../../../full/libs/graph/include", {public=true})
target_end()
