all:
	cd versatilepb; make
	cd raspix; make
	cd miyoo; make
	cd rk3326; make
	cd rk3128; make
	cd virt; make

clean:
	cd versatilepb; make clean
	cd raspix; make clean
	cd miyoo; make clean
	cd rk3326; make clean
	cd rk3128; make clean
	cd virt; make clean
