cores = 0 # 0 for cpu max cores
timer_freq = 1024 #kernel timer  FPS, 0 for default freq
uart_baud = 19200

max_proc_num = 128
max_task_per_proc = 64

dma_size = 134217728 #sys dma pool size in bytes, 0 for default (16/32/64MB by phy mem)
allocable_base_reserv_size = 0
allocable_top_reserv_size  = 0