all: basic_libs
	@echo "all done."

basic_libs:
	cd display;make
	cd graph;make
	cd fb;make
	cd fbd;make
	cd fonts;make
	cd upng; make
	cd console;make
	cd x;make
	cd cxx/cxx;make
	cd cxx/x++;make

clean:
	cd fb;make clean
	cd fbd;make clean
	cd graph;make clean
	cd fonts;make clean
	cd console;make clean
	cd display;make clean
	cd upng; make clean
	cd console;make clean
	cd x;make clean
	cd cxx/cxx;make clean
