all: basic_libs
	@echo "all done."

basic_libs:
	cd crc32;make
	cd zlib;make
	cd openlibm;make
	cd display;make
	cd graph;make
	cd ttf;make
	cd font;make
	cd minimp3;make
	cd fb;make
	cd fbd;make
	cd upng; make
	cd textview;make
	cd console;make
	cd x;make
	cd cxx/cxx;make
	cd cxx/x++;make
	cd cxx/widget;make

clean:
	cd crc32;make clean
	cd zlib;make clean
	cd openlibm;make clean
	cd fb;make clean
	cd fbd;make clean
	cd graph;make clean
	cd ttf;make clean
	cd textview;make clean
	cd console;make clean
	cd display;make clean
	cd font;make clean
	cd upng; make clean
	cd console;make clean
	cd x;make clean
	cd cxx/cxx;make clean
	cd cxx/x++;make clean
	cd cxx/widget;make clean
	cd minimp3;make clean
