target("etc")
    set_type("phony")
    install_dir("etc")    
    local rootfs_dir = get_rootfsdir()
    on_build(function(target)
        os.cp(target:scriptdir().."/qemu/full/init.rd", rootfs_dir.."etc/")
        os.cp(target:scriptdir().."/qemu/full/passwd", rootfs_dir.."etc/")
        os.cp(target:scriptdir().."/qemu/full/x", rootfs_dir.."etc/")
        os.cp(target:scriptdir().."/qemu/full/console.conf", rootfs_dir.."etc/")
    end)
target_end()
